UniverseWeb/config/routes.rb
UniverseWeb::Application.routes.draw do
  resources :entity_subtypes

  resources :entity_types

  resources :celestial_entities
  match 'about' => 'about#index'
  match 'games/matching' => 'matching#index'
  root :to => 'root#index'

end

UniverseWeb/app/models/celestial_entity.rb
class CelestialEntity < ActiveRecord::Base
  attr_accessible :description, :mass, :name, :orbit, :rotation, :radius, :volume, :density, :gravity, :parent_id, :entity_subtypeid
  
  belongs_to :entity_subtype, class_name: "EntitySubtype", foreign_key:'entity_subtypeid'
  
  #delegate :entity_type, :to => :entity_subtype, :allow_nil => true
end

UniverseWeb/app/controllers/celestial_entities_controller.rb
class CelestialEntitiesController < ApplicationController
  # GET /celestial_entities
  # GET /celestial_entities.json
  def index
    @celestial_entities = nil
    
    if params['entity_typeid']
      @celestial_entities = CelestialEntity.joins(:entity_subtype).where('entity_typeid = ?', params['entity_typeid'])
    else
      @celestial_entities = CelestialEntity.all

    end
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @celestial_entities }
    end
  end

  # GET /celestial_entities/1
  # GET /celestial_entities/1.json
  def show
    @celestial_entity = CelestialEntity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celestial_entity }
    end
  end

  # GET /celestial_entities/new
  # GET /celestial_entities/new.json
  def new
    @celestial_entity = CelestialEntity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @celestial_entity }
    end
  end

  # GET /celestial_entities/1/edit
  def edit
    @celestial_entity = CelestialEntity.find(params[:id])
  end

  # POST /celestial_entities
  # POST /celestial_entities.json
  def create
    @celestial_entity = CelestialEntity.new(params[:celestial_entity])

    respond_to do |format|
      if @celestial_entity.save
        format.html { redirect_to @celestial_entity, notice: 'Celestial entity was successfully created.' }
        format.json { render json: @celestial_entity, status: :created, location: @celestial_entity }
      else
        format.html { render action: "new" }
        format.json { render json: @celestial_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /celestial_entities/1
  # PUT /celestial_entities/1.json
  def update
    @celestial_entity = CelestialEntity.find(params[:id])

    respond_to do |format|
      if @celestial_entity.update_attributes(params[:celestial_entity])
        format.html { redirect_to @celestial_entity, notice: 'Celestial entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @celestial_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celestial_entities/1
  # DELETE /celestial_entities/1.json
  def destroy
    @celestial_entity = CelestialEntity.find(params[:id])
    @celestial_entity.destroy

    respond_to do |format|
      format.html { redirect_to celestial_entities_url }
      format.json { head :no_content }
    end
  end
end

UniverseWeb/app/helpers/celestial_entities_helper.rb
module CelestialEntitiesHelper
end

UniverseWeb/app/views/celestial_entities/_form.html.erb
<%= form_for(@celestial_entity) do |f| %>
  <% if @celestial_entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@celestial_entity.errors.count, "error") %> prohibited this celestial_entity from being saved:</h2>

      <ul>
      <% @celestial_entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :mass %><br />
    <%= f.number_field :mass %>
  </div>
  <div class="field">
    <%= f.label :orbit %><br />
    <%= f.number_field :orbit %>
  </div>
  <div class="field">
    <%= f.label :rotation %><br />
    <%= f.number_field :rotation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

UniverseWeb/app/views/celestial_entities/edit.html.erb
<h1>Editing celestial_entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @celestial_entity %> |
<%= link_to 'Back', celestial_entities_path %>

UniverseWeb/app/views/celestial_entities/index.html.erb
<h1>Celestial Entities</h1>

<ul class='nowrap'>
<% @celestial_entities.each do |celestial_entity| %>
  <li  onclick='window.open("<%= url_for(celestial_entity) %>");' >
    <%= image_tag 'celestial_entities/' + celestial_entity.name + '.jpg', :class => 'thumbnail' %>
    <div><%= celestial_entity.name %></div>
  </li>
<% end %>
</ul>

<!--<%= link_to 'New Celestial entity', new_celestial_entity_path %>-->

UniverseWeb/app/views/celestial_entities/new.html.erb
<h1>New celestial_entity</h1>

<%= render 'form' %>

<%= link_to 'Back', celestial_entities_path %>

UniverseWeb/app/views/celestial_entities/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @celestial_entity.name %>
</h1>
<%= image_tag 'celestial_entities/' + @celestial_entity.name + '.jpg' %>

<p>
  <b>Description:</b>
  <%= @celestial_entity.description %>
</p>

<p>
  <b>Mass:</b>
  <%= @celestial_entity.mass %>
</p>

<p>
  <b>Orbit:</b>
  <%= @celestial_entity.orbit %>
</p>

<p>
  <b>Rotation:</b>
  <%= @celestial_entity.rotation %>
</p>


<!--<%= link_to 'Edit', edit_celestial_entity_path(@celestial_entity) %> -->
<%= link_to 'All Celestial Entities', celestial_entities_path %>