UniverseWeb/config/routes.rb
UniverseWeb::Application.routes.draw do
  resources :entity_subtypes

  resources :entity_types

  resources :celestial_entities
  match 'about' => 'about#index'
  match 'games/matching' => 'matching#index'
  root :to => 'root#index'

end

UniverseWeb/app/controllers/entity_types_controller.rb
class EntityTypesController < ApplicationController
  # GET /entity_types
  # GET /entity_types.json
  def index
    @entity_types = EntityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entity_types }
    end
  end

  # GET /entity_types/1
  # GET /entity_types/1.json
  def show
    @entity_type = EntityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity_type }
    end
  end

  # GET /entity_types/new
  # GET /entity_types/new.json
  def new
    @entity_type = EntityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity_type }
    end
  end

  # GET /entity_types/1/edit
  def edit
    @entity_type = EntityType.find(params[:id])
  end

  # POST /entity_types
  # POST /entity_types.json
  def create
    @entity_type = EntityType.new(params[:entity_type])

    respond_to do |format|
      if @entity_type.save
        format.html { redirect_to @entity_type, notice: 'Entity type was successfully created.' }
        format.json { render json: @entity_type, status: :created, location: @entity_type }
      else
        format.html { render action: "new" }
        format.json { render json: @entity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entity_types/1
  # PUT /entity_types/1.json
  def update
    @entity_type = EntityType.find(params[:id])

    respond_to do |format|
      if @entity_type.update_attributes(params[:entity_type])
        format.html { redirect_to @entity_type, notice: 'Entity type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entity_types/1
  # DELETE /entity_types/1.json
  def destroy
    @entity_type = EntityType.find(params[:id])
    @entity_type.destroy

    respond_to do |format|
      format.html { redirect_to entity_types_url }
      format.json { head :no_content }
    end
  end
end

UniverseWeb/app/helpers/entity_types_helper.rb
module EntityTypesHelper
end

UniverseWeb/app/views/entity_types/_form.html.erb
<%= form_for(@entity_type) do |f| %>
  <% if @entity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity_type.errors.count, "error") %> prohibited this entity_type from being saved:</h2>

      <ul>
      <% @entity_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

UniverseWeb/app/views/entity_types/edit.html.erb
<h1>Editing entity_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity_type %> |
<%= link_to 'Back', entity_types_path %>

UniverseWeb/app/views/entity_types/index.html.erb
<h1>Listing entity_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entity_types.each do |entity_type| %>
  <tr>
    <td><%= entity_type.name %></td>
    <td><%= link_to 'Show', entity_type %></td>
    <td><%= link_to 'Edit', edit_entity_type_path(entity_type) %></td>
    <td><%= link_to 'Destroy', entity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entity type', new_entity_type_path %>

UniverseWeb/app/views/entity_types/new.html.erb
<h1>New entity_type</h1>

<%= render 'form' %>

<%= link_to 'Back', entity_types_path %>

UniverseWeb/app/views/entity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entity_type.name %>
</p>


<%= link_to 'Edit', edit_entity_type_path(@entity_type) %> |
<%= link_to 'Back', entity_types_path %>