UniverseWeb/config/routes.rb
UniverseWeb::Application.routes.draw do
  resources :entity_subtypes

  resources :entity_types

  resources :celestial_entities
  match 'about' => 'about#index'
  match 'games/matching' => 'matching#index'
  root :to => 'root#index'

end

UniverseWeb/app/controllers/entity_subtypes_controller.rb
class EntitySubtypesController < ApplicationController
  # GET /entity_subtypes
  # GET /entity_subtypes.json
  def index
    @entity_subtypes = EntitySubtype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entity_subtypes }
    end
  end

  # GET /entity_subtypes/1
  # GET /entity_subtypes/1.json
  def show
    @entity_subtype = EntitySubtype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity_subtype }
    end
  end

  # GET /entity_subtypes/new
  # GET /entity_subtypes/new.json
  def new
    @entity_subtype = EntitySubtype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity_subtype }
    end
  end

  # GET /entity_subtypes/1/edit
  def edit
    @entity_subtype = EntitySubtype.find(params[:id])
  end

  # POST /entity_subtypes
  # POST /entity_subtypes.json
  def create
    @entity_subtype = EntitySubtype.new(params[:entity_subtype])

    respond_to do |format|
      if @entity_subtype.save
        format.html { redirect_to @entity_subtype, notice: 'Entity subtype was successfully created.' }
        format.json { render json: @entity_subtype, status: :created, location: @entity_subtype }
      else
        format.html { render action: "new" }
        format.json { render json: @entity_subtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entity_subtypes/1
  # PUT /entity_subtypes/1.json
  def update
    @entity_subtype = EntitySubtype.find(params[:id])

    respond_to do |format|
      if @entity_subtype.update_attributes(params[:entity_subtype])
        format.html { redirect_to @entity_subtype, notice: 'Entity subtype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity_subtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entity_subtypes/1
  # DELETE /entity_subtypes/1.json
  def destroy
    @entity_subtype = EntitySubtype.find(params[:id])
    @entity_subtype.destroy

    respond_to do |format|
      format.html { redirect_to entity_subtypes_url }
      format.json { head :no_content }
    end
  end
end

UniverseWeb/app/helpers/entity_subtypes_helper.rb
module EntitySubtypesHelper
end

UniverseWeb/app/views/entity_subtypes/_form.html.erb
<%= form_for(@entity_subtype) do |f| %>
  <% if @entity_subtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity_subtype.errors.count, "error") %> prohibited this entity_subtype from being saved:</h2>

      <ul>
      <% @entity_subtype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

UniverseWeb/app/views/entity_subtypes/edit.html.erb
<h1>Editing entity_subtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity_subtype %> |
<%= link_to 'Back', entity_subtypes_path %>

UniverseWeb/app/views/entity_subtypes/index.html.erb
<h1>Listing entity_subtypes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entity_subtypes.each do |entity_subtype| %>
  <tr>
    <td><%= entity_subtype.name %></td>
    <td><%= link_to 'Show', entity_subtype %></td>
    <td><%= link_to 'Edit', edit_entity_subtype_path(entity_subtype) %></td>
    <td><%= link_to 'Destroy', entity_subtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entity subtype', new_entity_subtype_path %>

UniverseWeb/app/views/entity_subtypes/new.html.erb
<h1>New entity_subtype</h1>

<%= render 'form' %>

<%= link_to 'Back', entity_subtypes_path %>

UniverseWeb/app/views/entity_subtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entity_subtype.name %>
</p>


<%= link_to 'Edit', edit_entity_subtype_path(@entity_subtype) %> |
<%= link_to 'Back', entity_subtypes_path %>